# 前期准备{#prep}

## GitHub

请注册一个 [GitHub](https://github.com/) 账号，编程的入门票。用户名请认真起。如果你之后建个人网站不想买域名的话，你可以用免费的 `你的用户名.github.io`。所以如果用户名起得很丑的话，你个人网站的未来网址相应地也会很丑。

## 终端{#terminal}

如果你用的是苹果系统或者 Linux 系统，终端 (Terminal) 是自带的。如果你用的是 Windows 系统，终端的选取可以看看 [这个讨论](https://www.v2ex.com/t/514297)。我不怎么用 Windows，所以不是特别了解。上述讨论中 [powershell](https://docs.microsoft.com/zh-cn/powershell/scripting/windows-powershell/install/installing-windows-powershell?view=powershell-7.1), [cmder](https://cmder.net/), [wsltty](https://github.com/mintty/wsltty) 和 git bash 出现的频率比较高。你可以自己试试看哪个好用。

## 文本编辑器{#text-editor}

文本编辑器 (Text Editor) 是程序员用来吃饭的家伙。每个人的喜好不同，[Sublime Text](https://www.sublimetext.com/), [VS Code](https://code.visualstudio.com/) 和 [vim](https://www.vim.org/download.php) 这三个貌似很多人用，而且也都是免费的。我比较习惯用 Sublime Text。

## 英语{#English}

如果你对编程是认真的，不要抗拒学英语。你现在看到的主要编程语言，`Java`, `Python`, `Ruby`, `Go`, `JavaScript`, `R`, `C` 等都是西方人创造的，因此最主要和最新的学习资料肯定是英文的。编译类的教材在一定程度上可以缓解这个问题，但当资料非常新的时候，你只能眼巴巴地等翻译。其次，GitHub 上主要开源项目的文档是英文的，这个估计不会有人会去翻译。如果你看不懂，就没办法使用，在使用中碰到问题也没办法跟原作者沟通。另外，学编程就是一个持续不断碰到问题、解决问题的过程，而很多你碰到的问题早就有人在 [StackOverflow](https://stackoverflow.com/)上（用英语）问过和回答过了。
